# Generated by Django 3.2.6 on 2023-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="Birthdate"),
        ),
    ]
