# Generated by Django 3.2.6 on 2023-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
