# Generated by Django 3.2.6 on 2023-04-20 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0003_auto_20230420_0001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="granted_date",
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 20)),
            preserve_default=False,
        ),
    ]
