# Generated by Django 3.2.6 on 2023-04-20 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0004_alter_permission_granted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="granted_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
