# Generated by Django 3.2.6 on 2023-04-20 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0005_alter_permission_granted_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="permission_id",
        ),
        migrations.AlterField(
            model_name="permission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
